---
- name: Configure SoftHSM token for X-Road
  become: true
  when:
    - "'ubuntu_hsm_ss' in group_names"
  block:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install X-Road hardware token addon
      apt:
        name: xroad-addon-hwtokens
        state: present

    - name: Install SoftHSM2
      apt:
        name: softhsm2
        state: present

    - name: Ensure 'xroad' user is in 'softhsm' group
      user:
        name: xroad
        append: yes
        groups: softhsm

    - name: Ensure devices.ini exists
      file:
        path: "/etc/xroad/devices.ini"
        state: touch
        owner: root
        group: root
        mode: "0644"

    - name: Configure SoftHSM as a hardware token in X-Road devices.ini
      blockinfile:
        path: "/etc/xroad/devices.ini"
        marker: "# {mark} ANSIBLE MANAGED BLOCK (SoftHSM)"
        block: |
          [softhsm2]
          library = /usr/lib/softhsm/libsofthsm2.so
          os_locking_ok = true
          library_cant_create_os_threads = true

    - name: Check existing SoftHSM slots for token label
      command: softhsm2-util --show-slots
      register: softhsm_slots
      changed_when: false

    - name: Initialize SoftHSM token (idempotent if label already present)
      command: >
        softhsm2-util --init-token
        --slot 0
        --label "{{ hwtokens_label }}"
        --so-pin "{{ hwtokens_so_pin }}"
        --pin "{{ hwtokens_user_pin }}"
      when: softhsm_slots.stdout is not search("Label\\s*:\\s*{{ hwtokens_label | regex_escape() }}")
      register: init_result
      changed_when: init_result.rc == 0

    - name: Show token initialization status
      debug:
        msg: >-
          {{ "Token already present; no changes made."
             if softhsm_slots.stdout is search("Label\\s*:\\s*{{ hwtokens_label | regex_escape() }}")
             else "The token has been initialized." }}
          
    - name: Recursively chown tokens to xroad
      become: true
      ansible.builtin.file:
        path: /var/lib/softhsm/tokens
        state: directory
        owner: xroad
        recurse: yes